### ISSUE TITLE
Web Tool does not work

### ISSUE THREAD

**Issue by Vitexus** [paul-thebaud/phpunit-generator#1]
Upload adn editor works well but, generator itself is broken. I obtain only empty response. Please help

**Comment by KillianH** [comment]
I'll fix this ! Sorry for the inconvenience

**Comment by Vitexus** [comment]
Great! ( also you can refresh  certificate on doc's site https://doc.phpunitgen.io/en/terminal.html   ;)

![obrazek](https://user-images.githubusercontent.com/2621130/52229053-37637500-28b4-11e9-9175-3325bc91ab07.png)

Thanks!

**Comment by paul-thebaud** [comment]
@Vitexus We are currently updating certificates, we'll keep you in touch when it's done ;)

**Comment by KillianH** [comment]
> Great! ( also you can refresh certificate on doc's site https://doc.phpunitgen.io/en/terminal.html ;)
> 
> ![obrazek](https://user-images.githubusercontent.com/2621130/52229053-37637500-28b4-11e9-9175-3325bc91ab07.png)
> 
> Thanks!

Yep I've broke everything ...

**Comment by KillianH** [comment]
@Vitexus should be fixed. Can you retry ?

**Comment by Vitexus** [comment]
Confirm - Works well.
Excellent work boys! 
Thanks

**Comment by KillianH** [comment]
You're welcome 👍

**Comment by igronus** [comment]
Happened again. Expired: Sunday, 5 May 2019.

**Comment by paul-thebaud** [comment]
We'll fix that. Thank you for the reporting. @KillianH can you update the certificate please?

**Comment by KillianH** [comment]
Yep. Sorry. I'll try to fix that tonight. It's a pain in the butt to handle this certificate because it's a wildcard issued with the old beta of let's encrypt.

**Comment by KillianH** [comment]
It's back. Sorry for the inconvenience. You can close the issue @paul-thebaud

**Comment by paul-thebaud** [comment]
Thanks @KillianH for the quick fix!
