### ISSUE TITLE
Can you up dependency on nikic/php-parser to version 4 ?  

### ISSUE THREAD

**Issue by dallgoot** [paul-thebaud/phpunit-generator#2]
Using Composer Phpunitgen requirements enters in conflicts with some others packages : 
- apigen
- phpmetrics
that both also requires  nikic/php-parser but at version 4.

Is it possible to up on the new version of  nikic/php-parser ?

**Comment by paul-thebaud** [comment]
Hi @dallgoot,

The package have been updated to use `nikic/php-parser` version `4.x`.

You can update the package version to the latest release : `2.1.5`.

**Comment by paul-thebaud** [comment]
Closing this as it should be fixed.

@dallgoot, fell free to reopen if you encounter any issue about this.

**Comment by dallgoot** [comment]
Sorry for the response delay @paul-thebaud ...
Thank you very much for your quick actionr 👍
