### ISSUE TITLE
Current state of project?

### ISSUE THREAD

**Issue by TomasVotruba** [paul-thebaud/phpunit-generator#3]
Hi,

I randomly came across this tool today. I had similar idea for months in my head, so it was nice surprise :)

*0 % coverage? Run some tool... 95 % coverage* :+1:

I work on a tool https://github.com/rectorphp/rector, that basically handles all the possible upgrade/migration scenarios, that PHP community might need. 

Rector also does huge migrations like Zend 1 to Symfony 5 under 2-4 weeks. But to make it smooth and stable, big code coverage is required, where 1-2 % code coverage really is.

I'm exploring options adding this there/using is. Seeing only 34 stars, I'm said this is not more popular in PHP community (I didn't look at code nor features yet)

So my question would be, what are your plans? Like support PHPUnit 9? Framework testing migration like Symfony Kernel services, etc.?

**Comment by paul-thebaud** [comment]
Hi,

Thank you for the issue.

Firstly, the goal of this tool is not to generate the full tests (it does not makes sense), but the tests skeletons.

I am currently working on a new version of PhpUnitGen which is decomposed in 3 new repositories:
- [phpunitgen-core](https://github.com/paul-thebaud/phpunitgen-core)
- [phpunitgen-console](https://github.com/paul-thebaud/phpunitgen-console)
- [phpunitgen-webapp](https://github.com/paul-thebaud/phpunitgen-webapp)

This project is a fairly better version of the actual tool. It is better coded, more modular and maintenable. I think it is fully compatible with PHPUnit 9. About Symfony, I don't understand what you said, I mainly use Laravel.

It is currently in alpha stage. Could you take a look at it and give me your through?

The web application is not deployed for the moment, so I suggest you to install it locally. This will allow you to quickly try out the application and look at the documentation (which is still in progress).

If you have any other questions/suggestions, feel free :)

**Comment by paul-thebaud** [comment]
Hi @TomasVotruba,

You created this issue 18 days ago without updating it. Did I answer your question? Did you look at the new repositories?

Thanks.

**Comment by TomasVotruba** [comment]
Hi, sorry, I didn't have time, working on @rectorphp
I might use it at one project I'm currently migrating from CakePHP to Symfony. But I don't know much time does it take.

Thank you for the links!

**Comment by paul-thebaud** [comment]
No problem, feel free if you need something else.

**Comment by paul-thebaud** [comment]
Hi @TomasVotruba and everyone who's looking at this issue. Sorry I forget to ping you, but new version is now released as stable! Enjoy it :)
